jmeter-config:
  image: busybox
  container_name: jmeter-config 
  volumes:
      - /configuration 

jmeter:
  image: kurron/docker-monitor-jmeter 
  container_name: monitor-jmeter
  hostname: jmeter
# volumes_from:
#     - jmeter-config 
  restart: always
  net: host

